# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Tingbot Ocean
email: hello@tingbot.com
description: > # this means to ignore newlines until "baseurl:"
  The open source app store for Tingbot!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ocean.tingbot.com" # the base hostname & protocol for your site
twitter_username: thetingbot
github_username:  tingbot

# Build settings
markdown: kramdown
